# Dockerfile.ubuntu
FROM ubuntu:latest
RUN apt-get update && apt-get install -y --no-install-recommends \
    ttyd \
    tini \
    bash \
    mc \
    ca-certificates \
    smbclient \
    && rm -rf /var/lib/apt/lists/*

RUN ls / > /etc/system_dirs_snapshot.txt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7681
WORKDIR /root
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/entrypoint.sh"]