# Dockerfile.alpine
FROM alpine:3.24
RUN apk add --no-cache \
    ttyd \
    tini \
    bash \
    mc \
    ca-certificates \
    samba-client \
    tmux  \
    cifs-utils \
    p7zip \
    netcat-openbsd \
    && rm -rf /var/cache/apk/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && adduser -D -h /home/mcuser mcuser

EXPOSE 7681
WORKDIR /home/mcuser
USER mcuser

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD nc -z localhost 7681 || exit 1

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/entrypoint.sh"]